basePath: /
definitions:
  models.Author:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.Book:
    properties:
      author:
        $ref: '#/definitions/models.Author'
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: http://libraryapi.com
  description: This is a simple library API
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Library API
  version: "1.0"
paths:
  /authors:
    get:
      consumes:
      - application/json
      description: Get all authors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Author'
            type: array
      summary: Get all authors
      tags:
      - Authors
    post:
      consumes:
      - application/json
      description: Create author
      parameters:
      - description: Dados do author
        in: body
        name: author
        required: true
        schema:
          $ref: '#/definitions/models.Author'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create author
      tags:
      - Authors
  /authors/{id}:
    delete:
      consumes:
      - application/json
      description: Delete author
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Delete author
      tags:
      - Authors
    get:
      consumes:
      - application/json
      description: Get author by id
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Author'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get author by id
      tags:
      - Authors
    put:
      consumes:
      - application/json
      description: Update author
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      - description: Dados do author
        in: body
        name: author
        required: true
        schema:
          $ref: '#/definitions/models.Author'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update author
      tags:
      - Authors
  /books:
    get:
      consumes:
      - application/json
      description: Get all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Book'
            type: array
      summary: Get all books
      tags:
      - Books
    post:
      consumes:
      - application/json
      description: Create book
      parameters:
      - description: Dados do Book
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create book
      tags:
      - Books
  /books/{id}:
    delete:
      consumes:
      - application/json
      description: Delete book
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Delete book
      tags:
      - Books
    get:
      consumes:
      - application/json
      description: Get book by id
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get book by id
      tags:
      - Books
    put:
      consumes:
      - application/json
      description: Update book
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      - description: Dados do Book
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update book
      tags:
      - Books
swagger: "2.0"
